---
- name: gather facts
  hosts: all
  gather_facts: yes

- name: install keepalive
  hosts: HAproxy
  become: yes
  roles:
     - keepalive

- name: snmpd haproxy
  hosts: HAproxy
  become: yes
  roles:
     - haproxy
     #- webservers

- name: snmpd nodes
  hosts: webservers
  become: yes
  roles:
     - webservers

- name: install monitoring stack
  hosts: monitorserver
  become: yes
  roles:
     - prometheus
     - grafana

- name: install node-exporter
  hosts: webservers
  become: yes
  roles:
     - nodes-exporter
