---
- name : sudo wait     
  become: yes  
  shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

#- name:start Keepalived
#  become: yes
#  tasks:
- name: Ensure Keepalived service is running
  systemd:
        name: keepalived
        enabled: yes

#- name: restart keepalived
 # service:
  #      name: keepalived
   #     state: restarted
        
- name: start keepalived
  service:
        name: keepalived
        state: started
