---
- name : sudo wait     
  become: yes  
  shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

- name: restart keepalived
  service:
    name: keepalived
    state: started
