---
# tasks file for roles
    - name: update HAproxy
      apt:
        update_cache: yes

    - name: Installing HAPROXY
      apt:
        name: haproxy
        state: present
        update_cache: true

    - name: Configure haproxy
      template:
             src: haproxy.cfg.j2
             dest: /etc/haproxy/haproxy.cfg

    - name: Restart haproxy
      service:
        name: haproxy
        state: restarted

    - name: apt update
      apt:
        update_cache: true

    - name: Installing Nginx
      apt:
        name: nginx
        update_cache: yes
        state: latest

    - name: configure nginx udp port
      template:
             src: nginxport.conf
             dest: /etc/nginx/sites-available/default

    - name: configure udp loadbalancing
      template:
             src: nginxlb.conf
             dest: /etc/nginx/nginx.conf

    - name: Restart Nginx
      service:
            name: nginx
            state: restarted
    - name: apt update
      apt:
        update_cache: true










