---
- name : sudo wait
  become: yes
  shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

- name: gather server ip addresses
  setup:
      filter: ansible_default_ipv4.address     

- name: update and install prometheus
  apt:
    name: prometheus
    state: latest
    update_cache: yes
    cache_valid_time: 3600
- name: prometheus args
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
    mode: 0644
    owner: root
    group: root
  notify: restart_prometheus
- name: prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_dir_configuration }}/prometheus.yml"
    mode: 0755
    owner: prometheus
    group: prometheus
  notify: reload_prometheus
- name: start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes


#- name: Install Prometheus, Grafana, and node_exporter
 # hosts: bastion-server
  #become: true
  
  #tasks:
#    - name: Install Prometheus
 #     apt:
  #      name: prometheus
   #     state: present

   # - name: Configure Prometheus
    #  template:
     #   src: prometheus.yml.j2
      #  dest: /etc/prometheus/prometheus.yml
       # owner: prometheus
       # group: prometheus
       # mode: 0644
     # notify: 
      #  - restart prometheus
    
   # - name: Start Prometheus
    #  service:
     #   name: prometheus
      #  state: started
       # enabled: true

   # - name: Install Grafana
    #  apt:
     #   name: grafana
      #  state: present

  #  - name: Configure Grafana
   #   template:
    #    src: grafana.ini.j2
     #   dest: /etc/grafana/grafana.ini
      #  owner: grafana
       # group: grafana
        #mode: 0644
     # notify: 
      #  - restart grafana
    
   # - name: Start Grafana
    #  service:
     #   name: grafana-server
      #  state: started
       # enabled: true

   # - name: Download node_exporter
    #  get_url:
      #  url: https://github.com/prometheus/node_exporter/releases/download/v1.2.2/node_exporter-1.2.2.linux-amd64.tar.gz
     #   dest: /tmp/node_exporter.tar.gz

   # - name: Extract node_exporter
    #  unarchive:
     #   src: /tmp/node_exporter.tar.gz
      #  dest: /opt/
       # remote_src: true
        #creates: /opt/node_exporter-1.2.2/

  #  - name: Configure node_exporter
   #   copy:
    #    src: node_exporter.service
     #   dest: /etc/systemd/system/node_exporter.service
      #  owner: root
       # group: root
       # mode: 0644
     # notify:
      #  - restart node_exporter

   # - name: Start node_exporter
    #  service:
     #   name: node_exporter
      #  state: started
       # enabled: true

 # handlers:
#    - name: restart prometheus
 #     service:
  #      name: prometheus
   #     state: restarted
    
   # - name: restart grafana
    #  service:
     #   name: grafana-server
      #  state: restarted
    
   # - name: restart node_exporter
    #  service:
     #   name: node_exporter
      #  state: restarted


# tasks file for roles/prometheus
#- name: update and install prometheus
 # apt:
  #  name: prometheus
   # state: latest
   # update_cache: yes
    #cache_valid_time: 3600
#- name: prometheus args
 # template:
  #  src: prometheus.j2
   # dest: /etc/default/prometheus
   # mode: 0644
   # owner: root
   # group: root
  #notify: restart_prometheus
#- name: prometheus configuration file
 # template:
  #  src: prometheus.yml.j2
   # dest: "{{ prometheus_dir_configuration }}/prometheus.yml"
   # mode: 0755
   # owner: prometheus
   # group: prometheus
 # notify: reload_prometheus
#- name: start prometheus
 # systemd:
  #  name: prometheus
   # state: started
    #enabled: yes
